imports:
    - { resource: ../common.yml }

services:
    drsoft_fr.module.recaptcha.module:
        class: drsoftfrrecaptcha
        public: true

    drsoft_fr.module.recaptcha.install.factory.installer_factory:
        class: DrSoftFr\Module\ReCaptcha\Install\Factory\InstallerFactory

    drsoft_fr.module.recaptcha.install.installer:
        class: DrSoftFr\Module\ReCaptcha\Install\Installer
        factory: 'drsoft_fr.module.recaptcha.install.factory.installer_factory:create'
        public: true
