services:
    # Form services
    drsoft_fr.module.recaptcha.form.data_provider.recaptcha_form_data_provider:
        class: DrSoftFr\Module\ReCaptcha\Form\DataProvider\ReCaptchaFormDataProvider
        arguments:
            - '@drsoft_fr.module.recaptcha.data.configuration.recaptcha_configuration'

    drsoft_fr.module.recaptcha.form.handler.recaptcha_form_handler:
        class: PrestaShop\PrestaShop\Core\Form\Handler
        arguments:
            - '@form.factory'
            - '@prestashop.core.hook.dispatcher'
            - '@drsoft_fr.module.recaptcha.form.data_provider.recaptcha_form_data_provider'
            - DrSoftFr\Module\ReCaptcha\Form\ReCaptchaType
            - 'DrSoftFrModuleReCaptchaSetting'
        public: true

    # setting form
    drsoft_fr.module.recaptcha.form.recaptcha_type:
        class: DrSoftFr\Module\ReCaptcha\Form\ReCaptchaType
        parent: 'form.type.translatable.aware'
        tags:
            - { name: form.type }
